webtalk_init -webtalk_dir /home/ugrads/a/abhi.bhattacharyya/ecen248/Lab 5/Lab 5.sim/sim_1/behav/xsim/xsim.dir/add_sub_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar  8 12:36:33 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211529552_1777552551_210721790_305" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8e1339cc-f636-4d92-91ad-a9dca9a6c940" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "523d1c6c63a6443c9a630a5894243a16" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.9.2009 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3631.903 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "320 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124520_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4234117466 -regid "211529552_1777552551_210721790_305" -xml /home/ugrads/a/abhi.bhattacharyya/ecen248/Lab 5/Lab 5.sim/sim_1/behav/xsim/xsim.dir/add_sub_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ugrads/a/abhi.bhattacharyya/ecen248/Lab 5/Lab 5.sim/sim_1/behav/xsim/xsim.dir/add_sub_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ugrads/a/abhi.bhattacharyya/ecen248/Lab 5/Lab 5.sim/sim_1/behav/xsim/xsim.dir/add_sub_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
